# Generated by Django 5.2.3 on 2025-07-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_ticket_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
