# Generated by Django 5.2.3 on 2025-07-31 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_ticket_issue_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='issue_type',
        ),
    ]
