# Generated by Django 5.2.3 on 2025-07-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_ticket_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(choices=[('technical outage', 'Technical Outage'), ('cybersecurity incident', 'Cybersecurity Incident'), ('client complaint', 'Client Complaint'), ('sla breach', 'SLA Breach')], default='technical outage', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
    ]
