# Generated by Django 5.2.3 on 2025-08-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_ticket_current_escalation_level_escalationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='issue_type',
        ),
    ]
